# Generated by Django 5.0.6 on 2024-07-03 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_guitar_load_count_alter_guitar_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='guitar',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
