# Generated by Django 5.0.6 on 2024-07-03 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0005_guitar_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guitar',
            name='comentario',
            field=models.TextField(),
        ),
    ]
